version: '3'
services:
  postgres:
    image: 'postgres:latest'
  redis:
    image: 'redis:latest'
  nginx:
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - '3050:80'
  api:  
    # depends_on: 
    #  - postgres
    build:
      dockerfile: Dockerfile.dev
      context: ./server
    volumes:
      - /usr/local/app/node_modules
      - ./server:/usr/local/app/
    environment:
      # real hostname
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PGUSER=postgres
      - PGHOST=PGUSER=postgres
      - PGDATABASE=postgres
      - PGPASSWORD=postgres_password
      - PGPORT=5432
  client:
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    volumes:
      - /usr/local/app/node_modules
      - ./client:/usr/local/app/
  worker:
    build:
      dockerfile: Dockerfile.dev
      context: ./worker
    volumes:
      - /usr/local/app/node_modules
      - ./worker:/usr/local/app/
    environment: 
      # ip address
      - REDIS_HOST=redis
      - REDIS_PORT=6379
#  api: 
#    depends_on: 
#      - postgres
      
